application: rpiquicksell
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
