application: rpiquicksell
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

<<<<<<< HEAD
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
=======
- url: /*
  script: isbnsearch.py
>>>>>>> isbn
